### PR TITLE
A bunch of Damage and tiny detail tweaks.

### PR DESCRIPTION
**Pull request by KellionDev**
Hello! Well uh... I never really used Github for development before, so my apologies if I'm doing something wrong.
A-anyway,  since my ZScript or decorate or whatever skill is about as good as my knowledge in assembly (IE: Non-existent), I attempted to rebalance some of the weapons to improve gameplay flow. The code remains functional on my side, and I used GZDoom's 3.5 Vintage edition. I tested most of the weapons on Scythe 2's various levels and used MonsterScouter.pk3 to monitor the monster's HP.

I did this cause I realized balancing these weapons would be a royal **** if I did on the forums. Aka boost this slightly, nerf this slightly, buff it more, nerf, ad nauseum.

So anyway, there's a few things that still need... erm. fixing.
-Armor mixing is completely broken. (Just spawn random Armors and shields and mix them with a rocket launcher, the bugs are spectacular.)
-The BioRifle's altfire has that delay when its halfway full when firing, after gazing at the code I noticed you're doing some kind of multi-stage firing sequence. Perhaps would it better to default to the previous fill 'state' to increase the firing speed? Anyways, as expected, when its full it fires instantly.

And to clarify some suggestions back in the forum.

-The Invisibility might just be a quirk of doom's engine. It just works randomly and unreliably.
-To clarify the Redeemer's missing blast. In DiabolusEx's map, in the digital world where there's a BFG/Redeemer.  I shot the cyberdemon behind the final red wall while guiding the redeemer, in the back. And the Cyberdemon was idle. Keep in mind I didn't retest this... so it might be a one-time glitch.
-On the Biorifle's expanding sludge: I must be mistaken, I played Ut 2004 mostly while Ut99 is mostly early childhood material, so my memory must be a little wonky at times. I can't really confirm it though, but the Wiki says this feature is a novelty in 2004 so... that's that.
-The Chainsaw's lameness is still there.
-Your tweaks in terms of speed and responsiveness felt great! 
-Don't really have a new ammo replacement sheet yet, will need to play a few wads to figure that out. Sorry!
-I think the missiles look awesome! Btw, I'll need to play a few Wads to figure out if the Warhead drop rates feel right. After all, the Redeemer is alot more powerful than the BFG.

And things I possibly borked:
-The Flak cannon now shoots more projectiles. It might need a bit of tweak in the sound and particle department to get back in perfect order.
-The Biorifle's biggest blob creates alot of other blobs. Like, too many blobs.

Hope I helped! :D

Edit: Nerfed the flak cannon too hard. In battle I turn to most other weapons instead of the flak cannon when in close range. Possibly not effective enough, and the low ammo capacity just makes the problem worse, gotta have to balance it better. Keep this in mind.

Edit2: I'll be attempting to rebalance the Flak Cannon to get the right 'feel' of it. In UT, the Flak Cannon is supposedly the king of corner fighting and tight ranges. My idea for replicating this is to start it off with really good damage and reduce it rapidly over a distance through the use of functions. I'm still not sure how to do that in ZScript, but I got ideas.

Also, not exactly sure how ZScript works and how you can tweak armor with it, but here's my suggestion for fixing it.
When you get the shield, you store the other armor pieces as a separate value and add them it to the armor total. (Which now all that matters is around 150 of it) This should solve the problem that I noticed that other armor pieces also take damage while you have the shield.
This can also be used with other armor pieces when combined to result a 75% protection armor. Or Chestplate+thighArmor. What I see is that you really have to store the values separately, cause UT keeps separate armor hitpoints, unlike doom.

Again, not sure how you will do this in code. I'd do it myself, but all I know is C# and Unity. ZScript and Decorate is kinda far from my specialty.
Best of luck!

### CODE REVIEW

**Comment by OrdinaryMagician** [comment]
Could you clean this up and squash it in a single commit? Also, there's something wrong with the flak cannon changes, the diff shows that the whole file is changed, making it hard to know what exactly is different.

**Comment by KellionDev** [comment]
I commented next to each change. In any case, I'm working on the Flak Cannon's damage right now. So... a new change might be in soon.

Sorry about the mess. I'm still new with this site, I'll try to figure it out. :P

Side note here: I'm also taking notes of the current weapon's DPS of the various fire modes to work out imbalances, I'll send you a sheet once its done.

**Comment by OrdinaryMagician** [comment]
The whole thing about flak chunk damage falling off with distance travelled can be easily done, by the way.

**Comment by KellionDev** [comment]
Holy shit, what a rabbit hole...
Yeah... these commits will take a while to fix.

**Comment by OrdinaryMagician** [comment]
It's ok, I can try and do most of the stuff myself over here.

**Comment by KellionDev** [comment]
Do that, in any case. I fixed both the things I borked in my builds. The Flak Cannon's damage has been reset to normal levels, and I made damage falloff over distance. Its a pretty immense falloff, and I still think the Flak Cannon is on the higher end of OP.
On the minigun, in an effort to make it compete with the rest of the arsenal and... (The Double Enforcer, which prior to the tweak it actually had a bigger DPS). I made it spew lead 3 times faster, this gives a lot more DPS and gives some use to the enforcer ammo late game. Ammo burns away fast though.
Also fixed the abnormal additional sludging in the BioRifle after the change.

Unfortunately the Pulse rifle still got the short end of the stick. Gotta figure out what to do with it.

Sidenote here: I understand some of the balancing is straying a bit from the default UT99 mechanics, but I'm doing my best to mesh it to Doom's style. In any case, you'll be the judge once the build rolls around.

**Pull request closed without merging**
